// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSL2SE8S7kXHk7Skq3xwLOiNJvS08yOF0',
    appId: '1:641522497880:web:3f9f717572689af2608d2d',
    messagingSenderId: '641522497880',
    projectId: 'uas-mobile-programming-d1c81',
    authDomain: 'uas-mobile-programming-d1c81.firebaseapp.com',
    storageBucket: 'uas-mobile-programming-d1c81.firebasestorage.app',
    measurementId: 'G-P48G891GJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGor_ktMR1EqXPL5ykHZipij9i25PYIJ8',
    appId: '1:641522497880:android:c50cbb9ae950c433608d2d',
    messagingSenderId: '641522497880',
    projectId: 'uas-mobile-programming-d1c81',
    storageBucket: 'uas-mobile-programming-d1c81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhC6smclvQGyXJu8PWNGRU0LgdPvOE-Q',
    appId: '1:641522497880:ios:b94630c585ce865e608d2d',
    messagingSenderId: '641522497880',
    projectId: 'uas-mobile-programming-d1c81',
    storageBucket: 'uas-mobile-programming-d1c81.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWhC6smclvQGyXJu8PWNGRU0LgdPvOE-Q',
    appId: '1:641522497880:ios:b94630c585ce865e608d2d',
    messagingSenderId: '641522497880',
    projectId: 'uas-mobile-programming-d1c81',
    storageBucket: 'uas-mobile-programming-d1c81.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSL2SE8S7kXHk7Skq3xwLOiNJvS08yOF0',
    appId: '1:641522497880:web:b6586d8a078e0653608d2d',
    messagingSenderId: '641522497880',
    projectId: 'uas-mobile-programming-d1c81',
    authDomain: 'uas-mobile-programming-d1c81.firebaseapp.com',
    storageBucket: 'uas-mobile-programming-d1c81.firebasestorage.app',
    measurementId: 'G-Y5XBBMRENY',
  );
}
